# This workflow runs for every pull request to lint and test the proposed changes.

name: Check

on:
    pull_request:

jobs:
    # NPM install is done in a separate job and cached to speed up the following jobs.
    build_and_test:
        name: Build & Test
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest] # add windows-latest later
                node-version: [16, 18, 20, 22]

        steps:
            -
                uses: actions/checkout@v4
            -
                name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
            -
                name: Cache Node Modules
                if: ${{ matrix.node-version == 20 }}
                uses: actions/cache@v4
                with:
                    path: |
                        node_modules
                        build
                    key: cache-${{ github.run_id }}-v20
            -
                name: Install Dependencies
                run: npm install
            -
                name: Add localhost-test to Linux hosts file
                if: ${{ matrix.os == 'ubuntu-latest' }}
                run: sudo echo "127.0.0.1 localhost-test" | sudo tee -a /etc/hosts
#            -
#                name: Add localhost-test to Windows hosts file
#                if: ${{ matrix.os == 'windows-latest' }}
#                run: echo "`n127.0.0.1 localhost-test">>C:\Windows\System32\drivers\etc\hosts
            -
                name: Run Tests
                run: npm test

    lint:
        name: Lint
        needs: [build_and_test]
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v4
            -
                name: Use Node.js 20
                uses: actions/setup-node@v4
                with:
                    node-version: 20
            -
                name: Load Cache
                uses: actions/cache@v4
                with:
                    path: |
                        node_modules
                        build
                    key: cache-${{ github.run_id }}-v20
            -
                run: npm run lint
